README.md
Minor change to the README: API actions should only throw either an `ApiException` or its parent `OnfidoException`, rather than a generic `Exception`.
=> Update exceptions in README

onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/main/models/check.json, onfido-java/src/main/templates/Model.mustache, onfido-java/src/test/java/com/onfido/OnfidoTest.java
A few minor changes spotted during testing:
* The `report_ids` field was missing from check responses.
* Throw a `RuntimeException` if the api token is missing, otherwise you get a generic unauthorized error when making api calls
* The whitespace for the model template went weird at some point, so I've reverted that to make the generated models easier to read.
=> Add report ids field, check for apiToken

onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/test/java/com/onfido/OnfidoTest.java
Small fix for #16 - when doing `.apiToken(null)` you get a NPE and it isn't very easy to see why if you're doing something like this:
```java
Onfido.builder().apiToken(System.getenv("ONFIDO_API_TOKEN")).build();
```
I'm undecided on whether to do a 1.0.1 release for this or just wait for a future release
=> Handle passing a null apiToken

.travis.yml
Forking and opening a pull request causes the build to fail because of missing env vars in travis. This fixes that by not requiring those env vars unless you're releasing.
=> Fix travis file for forks

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/api/FileDownload.java, onfido-java/src/main/java/com/onfido/api/ResourceManager.java, onfido-java/src/test/java/com/onfido/integration/ApiIntegrationTest.java, onfido-java/src/test/java/com/onfido/integration/DocumentManagerTest.java, onfido-java/src/test/java/com/onfido/integration/LivePhotoManagerTest.java, onfido-java/src/test/java/com/onfido/integration/LiveVideoManagerTest.java
We currently close the download stream before you can actually download the file. A fix for #25 
Return the download as a byte array rather than an input stream. This is simpler for users of the library and means they don't have to worry about closing the input stream themselves.
We've decided it's okay to load the full image into memory, because it's limited to 10mb. We may need to improve how live videos are downloaded in the future, however this has lower usage.
I've considered this not a breaking change, because it currently doesn't work anyway. It could cause a compile error if a client was already using it and updated, but in that case their code would be failing at runtime instead.
Improved unit tests to check the actual content gets returned
Thanks @JakeBat for manually testing 👍
=> Fix downloads issue

README.md, onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/CheckManager.java, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/main/java/com/onfido/api/ApiJson.java, onfido-java/src/main/models/check.json, onfido-java/src/test/java/com/onfido/JsonObject.java, onfido-java/src/test/java/com/onfido/OnfidoTest.java, onfido-java/src/test/java/com/onfido/integration/CheckManagerTest.java, onfido-java/src/test/java/com/onfido/integration/DocumentManagerTest.java, onfido-java/src/test/java/com/onfido/integration/LivePhotoManagerTest.java, onfido-java/src/test/java/com/onfido/integration/LiveVideoManagerTest.java, onfido-java/src/test/java/com/onfido/webhooks/WebhookEventVerifierTest.java
* adds 'Download check' endpoint + test
* adds support for `webhook_ids`
* adds `privacy_notices_read_consent_given` to check object (no longer write only)
* bumps base URL versions to 3.1
* bumps version of library to 2.0.0
=> Adds API v3.1 additions, changes base URLs, adds tests, bumps version

onfido-java/src/main/models/address.json
Library does not yet allow for line1, line2, line3 in address object, so this adds functionality
https://documentation.onfido.com/#address-object
=> Adds line1, line2, line3 fields to address object for ID Enhanced

onfido-java/src/main/models/check.json
In api reference documentation this field discribed as request parameter, so, as I understand it, `redirect_uri` must be read-write
https://documentation.onfido.com/#create-check
=> Field Check.redirect_uri must be read-write

generate-models-maven-plugin/src/main/java/com/onfido/models/Property.java, onfido-java/pom.xml, onfido-java/src/main/models/check.json
Change the type to `Boolean` for `privacy_notices_read_consent_given` in Check class to account for when no value is passed during check creation and the parameter is returned as `null` in the check response as per documentation.
=> Check class to allow `null` values for privacy consent parameter

onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/test/java/com/onfido/integration/OnfidoIntegrationTest.java
This PR adds the ability for the customers to set a read timeout (defaults to 15 seconds) to the underlying HttpClient, also adds the ability to use a java.net.Proxy as per customer request.
=> Add the ability to specify proxy and the HttpClient read timeout.

onfido-java/src/main/models/check.json, onfido-java/src/main/models/driving_licence.json, onfido-java/src/test/java/com/onfido/integration/CheckManagerTest.java
The PR extends the Check.Request object to support [Driver's License Data Verification (DLDV) report](https://documentation.onfido.com/#drivers-license-data-verification-report). 
```java
Check check =
onfido.check.create(Check.request()
.applicantId("id")
.reportNames("us_driving_licence")
.usDrivingLicence(DrivingLicence.request().idNumber("12121212").stateCode("GA"))
);
```
the json sent to Onfido will look like this:
```json
{
"applicant_id":"id",
"report_names":["us_driving_licence"],
"us_driving_licence":{
"id_number":"12121212",
"issue_state":"GA"
}
}
```
=> Support for Driver's License Data Verification report

onfido-java/pom.xml
Upgrade okhttp3 dependency to 4.9.2 (was 4.2.2) to address CVE-2021-0341.
=> Upgrade okhttp3 dependency

.github/workflows/maven.yml, onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/api/ResourceManager.java
Changing User-Agent header provided at each request into `onfido-java/{version}` to make it similar to format used by other client libraries. It includes a change to CI to run checks also on branches with name starting with  `release/`.
=> Add information about library version into User-Agent header

onfido-java/pom.xml
This is to fix vulnerability CVE-2022-24329
=> Update okhttp3 version to 4.10.0 (was 4.9.2)

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/WorkflowRunManager.java, onfido-java/src/test/java/com/onfido/integration/WorkflowRunManagerTest.java
It adds a new [workflow run signed evidence PDF download endpoint](https://documentation.onfido.com/#retrieve-workflow-run-signed-evidence-file).
=> Add workflow run related evidence download endpoint

onfido-java/pom.xml
Upgrade okhttp3 dependency to 4.12.0 (was 4.10.0) to address [CVE-2023-3635](https://devhub.checkmarx.com/cve-details/CVE-2023-3635/).
=> Upgrade okhttp3 dependency to 4.12.0 (was 4.10.0)

src/test/java/com/onfido/integration/CheckTest.java, src/test/java/com/onfido/integration/LivePhotoTest.java, src/test/java/com/onfido/integration/ReportSchemasTest.java, src/test/java/com/onfido/integration/ReportTest.java, src/test/java/com/onfido/integration/TasksTest.java, src/test/java/com/onfido/integration/TestBase.java, src/test/java/com/onfido/integration/WorkflowRunOutputsTest.java, src/test/java/com/onfido/integration/WorkflowRunTest.java, src/test/java/com/onfido/utils/ProfileDataCapture.json
Add tests validating the outcome of Document and Facial Similarity reports, there should be no error deserialising the response when retrieving the reports.
The [output field of workflow runs](https://documentation.onfido.com/#workflow-run-object) is configured within Studio workflow builder and can yield anything the client configures.
The tests added validate there are no schema errors when the output is configured to be the result of a Profile Data Capture task, of a Document Report and of a Facial Similarity Photo Report.
=> Add tests focusing on Report schemas and workflow run outputs

.release.json, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/FileTransfer.java, src/main/java/com/onfido/api/DefaultApi.java, src/main/java/com/onfido/model/CompleteTaskDataBuilder.java, src/main/java/com/onfido/model/Report.java, src/test/java/com/onfido/FileTransferTest.java, src/test/java/com/onfido/integration/CheckTest.java, src/test/java/com/onfido/integration/DocumentTest.java, src/test/java/com/onfido/integration/IdPhotoTest.java, src/test/java/com/onfido/integration/LivePhotoTest.java, src/test/java/com/onfido/integration/LiveVideoTest.java, src/test/java/com/onfido/integration/MotionCaptureTest.java, src/test/java/com/onfido/integration/ReportSchemasTest.java, src/test/java/com/onfido/integration/TestBase.java, src/test/java/com/onfido/integration/WorkflowRunTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@e92d340b84690cce6851fa4a32530ac29911d75a (included)
- [Use FileTransfer object in tests](https://github.com/onfido/onfido-java/pull/118/commits/272564a9a42963166c50b3b87f71162e31b84558)
=> Refresh onfido-java after onfido-openapi-spec update (e92d340)

src/test/java/com/onfido/integration/ReportSchemasTest.java, src/test/java/com/onfido/integration/TestBase.java, src/test/java/com/onfido/integration/WorkflowRunTest.java
Use `getReportShared()` to access `getStatus()` method instead of `getActualInstance()` in [repeatRequestUntilStatusChanges](https://github.com/onfido/onfido-java/blob/master/src/test/java/com/onfido/integration/TestBase.java#L166) method.
=> test: improvements to Report Schema tests

.release.json, README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/api/DefaultApi.java, src/test/java/com/onfido/integration/WorkflowRunTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@54ce45f2138f044cc5cb40f6904dc7bc1a675be6 (included)
- [Add downloadEvidenceFolder test](https://github.com/onfido/onfido-java/pull/138/commits/a562919617f57702b372d3b0a6b56cc816ac9825)
=> Refresh onfido-java after onfido-openapi-spec update (54ce45f)

src/test/java/com/onfido/integration/ReportSchemasTest.java, src/test/java/com/onfido/integration/ReportTest.java, src/test/java/com/onfido/integration/TestBase.java, src/test/java/com/onfido/integration/WorkflowRunOutputsTest.java, src/test/java/com/onfido/integration/WorkflowRunTest.java
Evidence folder needs to be available before it can be downloaded. Fix the test by retrying the request until we no longer receive 404.
I also did some extra changes (increasing number of retries) to reduce test flakiness.
=> test: wait for evidence folder to be available

pom.xml
Trying to solve issue at delivery time reported below:
https://github.com/onfido/onfido-java/actions/runs/13440014944/job/37552016229
By applying what suggested below:
https://stackoverflow.com/a/70157413
=> Update Sonatype Staging Maven plugin version to allow delivery

pom.xml
Update nexus-staging-maven-plugin to avoid error: 
```
Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy (injected-nexus-deploy) on project onfido-api-java: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy failed: An API incompatibility was encountered while executing org.sonatype.plugins:nexus-staging-maven-plugin:1.6.7:deploy: java.lang.ExceptionInInitializerError: null
```
https://github.com/onfido/onfido-java/actions/runs/15022699142/job/42215925283
=> Update nexus staging maven plugin version

pom.xml
Update publishing configuration to use Central Publisher Portal:
- https://central.sonatype.org/publish/publish-portal-maven/
- https://dev.to/mxro/migrating-maven-namespace-to-central-portal-fgp
Taking the opportunity to bump `org.apache.commons:commons-lang3` version from 3.17.0 to 3.18.0 to fix [vulnerability](https://github.com/onfido/onfido-java/security/dependabot/2).
=> Update publishing configuration to use Central Publisher Portal

pom.xml
Add the deployment name which was missing. Wait until validated (instead of published); default timeout of 30 minutes ([doc](https://central.sonatype.org/publish/publish-portal-maven)) should be enough for that.
=> Update publishing configuration to use Central Publisher Portal (4)

.release.json, README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/api/DefaultApi.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@22e3bd3bc410d379ded0cdd592f71059fc0aee1d (included)
- None
=> Refresh onfido-java after onfido-openapi-spec update (22e3bd3)

.github/workflows/maven.yml, CHANGELOG.md
Fix CHANGELOG.md and improve CI to not run tests when commit is not coming from a PR (i.e. CHANGELOG update performed by the CI).
Take the opportunity for fixing a few security vulnerabilities:
- https://github.com/onfido/onfido-java/security/code-scanning/1
- https://github.com/onfido/onfido-java/security/code-scanning/2
=> Fix CHANGELOG.md and improve CI
