onfido-java/src/main/java/com/onfido/api/ResourceManager.java, onfido-java/src/main/java/com/onfido/managers/DocumentManager.java, onfido-java/src/main/java/com/onfido/managers/LivePhotoManager.java, onfido-java/src/test/java/com/onfido/api/DocumentManagerTest.java, onfido-java/src/test/java/com/onfido/api/LivePhotoManagerTest.java
Added null check when adding params to multipart bodies
An error was thrown when a null param was passed to the upload methods
Manual testing performed via a test class
=> Et 27 add null param handling

.maven.xml, .travis.yml, onfido-java/pom.xml
Updated travis.yml to correctly use the release profile, fixed GPG signing variables and setup, pom optimizations
A test deploy was done using these changes on the test-release branch: https://travis-ci.com/onfido/onfido-java/builds/148852257.
=> Fixing travis deployment script and maven config

onfido-java/src/main/models/document_id.json, onfido-java/src/main/models/report.json
=> Report model wrong documents list object type

onfido-java/pom.xml
Planning to release a couple of bugfixes
=> Bump to version 1.0.1

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/Onfido.java
=> Custom http client enhancement

onfido-java/pom.xml
Updating the timeout for nexus upload to fix intermittent timeout issue occurring during release jobs.
=> Increasing staging timeout settings to 10 minutes

onfido-java/pom.xml, onfido-java/src/main/models/report.json
Hi, i was working with web hooks. I noticed that documentation is not in sync with java library. Given report id, when you get details from onfido there is not check id related with that report. If i missed something please let me know.
=> check id added to report model json

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/main/java/com/onfido/api/Config.java, onfido-java/src/main/models/report.json, onfido-java/src/test/java/com/onfido/OnfidoTest.java, onfido-java/src/test/java/com/onfido/integration/ApiIntegrationTest.java
* Add support for api.ca.onfido.com
* Test region gets set correctly
* Minor version bump
* Update some descriptions to match the docs
=> Add Canada region support

README.md
Minor amendment re. CA region in builder example
=> Update README (CA region)

README.md, onfido-java/pom.xml, onfido-java/src/main/models/sdk_token.json
Updated sdk_token model for new parameter available for enterprise customers.
**Will not be merged in until backend changes are ready.**
=> Add new cross_device_url enterprise param to sdk_token model

onfido-java/pom.xml, onfido-java/src/main/models/check.json, onfido-java/src/main/models/webhook.json
=> Document ids for check request and webhook environments field name fixed

onfido-java/pom.xml, onfido-java/src/main/models/live_video.json
The challenge field in live video responses was incorrect: it should be an array of objects, not an object.
Manual testing.
=> Use correct type for live video challange

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/ExtractionManager.java, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/main/models/document_classification.json, onfido-java/src/main/models/extracted_data.json, onfido-java/src/main/models/extraction.json, onfido-java/src/test/java/com/onfido/integration/ExtractionManagerTest.java
Adding support for extractions endpoint per users requests
Credit to @akrasnoshchok for authoring the majority of these changes
=> Extractions endpoint

onfido-java/pom.xml, onfido-java/src/main/models/check.json
* Adds ability to pass `privacy_notices_read_consent_given` in check creation
=> Adds privacy_notices_read_consent_given

.github/workflows/maven.yml, onfido-java/pom.xml, onfido-java/src/main/models/check.json, onfido-java/src/test/java/com/onfido/integration/CheckManagerTest.java
* Add GitHub actions workflow
* Add pre-determined response sandbox functionality for Document report sub-results (and test)
* Add pre-determined response sandbox functionality for consider array report results (and test)
* Add test for `privacy_notices_read_consent_given`
=> Add GitHub actions workflow and pre-determined response functionality

.github/workflows/maven-publish.yml, onfido-java/pom.xml
=> Release of 2.1.0

README.md, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/test/java/com/onfido/OnfidoTest.java
=> Adds support for API v3.2

onfido-java/src/main/java/com/onfido/api/ApiJson.java, onfido-java/src/test/java/com/onfido/integration/ExtractionManagerTest.java
Issue Link:
https://github.com/onfido/onfido-java/issues/57
Handle empty string for LocalDate fields in extracted_data.
=> Handle empty string for LocalDate fields in extracted_data.

onfido-java/pom.xml
New minor version release for adding DLDV report support.
=> Bump to v2.4.0

onfido-java/pom.xml, onfido-java/src/main/models/applicant.json, onfido-java/src/main/models/consent.json
Fixes bug where consents array items didn't match the API definition
=> Fix consents param in applicant object

.github/workflows/maven.yml, onfido-java/pom.xml
Upgrade okhttp3 dependency to 4.9.2 (was 4.2.2) to address CVE-2021-0341 (retrofit v2.5).
=> Upgrade okhttp3 dependency to 4.9.2 (was 4.2.2)

.github/workflows/maven.yml, onfido-java/src/test/java/com/onfido/integration/ExtractionManagerTest.java, onfido-java/src/test/java/com/onfido/integration/TestBase.java, onfido-java/src/test/java/com/onfido/integration/WebhookManagerTest.java
- Update extraction manager tests
- Make tests more resilient
- Enable daily run of pipeline
=> Improve e2e tests and enable periodic pipeline execution

README.md, onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/test/java/com/onfido/OnfidoTest.java
Added a new minor version 3.6.0
Point all urls to this new version in the library
=> Point to new version 3.6

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/Onfido.java, onfido-java/src/main/java/com/onfido/WorkflowRunManager.java, onfido-java/src/main/models/workflow_run.json, onfido-java/src/test/java/com/onfido/integration/WorkflowRunManagerTest.java
Adds [WorkflowRun](https://documentation.onfido.com/#workflow-runs) resources
=> Add workflow_runs resources

onfido-java/pom.xml, onfido-java/src/main/java/com/onfido/WebhookManager.java, onfido-java/src/main/models/webhook_resend.json, onfido-java/src/main/models/webhook_resend_object.json, onfido-java/src/test/java/com/onfido/integration/WebhookManagerTest.java
- Add the ability to [resend webhooks](https://documentation.onfido.com/#resend-webhooks)
=> Add resend webhook

src/test/java/com/onfido/integration/ReportSchemasTest.java, src/test/java/com/onfido/integration/TestBase.java, src/test/java/com/onfido/integration/WatchlistMonitorTest.java, src/test/java/com/onfido/integration/WorkflowRunOutputsTest.java, src/test/java/com/onfido/integration/WorkflowRunTest.java
Add tests for:
- Watchlist monitors
- Workflow runs with custom inputs
- Timeline file endpoints
Improvements to how we retry requests on tests.
=> Add more tests

.github/workflows/maven.yml, .release.json, CHANGELOG.md, README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/FileTransfer.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@a34b6d86714f7f74da2d60a33a76ec3a693d264a (included)
- [Update CHANGELOG (and remove step in charge of that from CI for now)](https://github.com/onfido/onfido-java/pull/119/commits/5be6694fbd23fccb10d6d8c4ed6b442bbb5237b1)
=> Refresh onfido-java after onfido-openapi-spec update (a34b6d8)

.github/workflows/maven.yml, .release.json, README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/model/DocumentProperties.java, src/main/java/com/onfido/model/DocumentWithDriverVerificationReportAllOfProperties.java, src/test/java/com/onfido/integration/ReportSchemasTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@01ed1b5fe0f7490bfce54816504a9fec13b33862 (included)
- [Update tests after refresh, validate and update release in CI](https://github.com/onfido/onfido-java/pull/120/commits/bb0407e489a14194f544efc63a60b00350c4b028)
=> Refresh onfido-java after onfido-openapi-spec update (01ed1b5)

.release.json, README.md, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/JSON.java, src/main/java/com/onfido/model/DocumentProperties.java, src/main/java/com/onfido/model/DocumentPropertiesBarcode.java, src/main/java/com/onfido/model/DocumentWithDriverVerificationReportAllOfProperties.java, src/test/java/com/onfido/integration/ReportSchemasTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@d180eddd168dd95bf84bf7c8fe9f8c7e3c0c5494 (included)
- [Add test case for DocumentWithAddressInformation report](https://github.com/onfido/onfido-java/pull/134/commits/ff35972a69f93294b47fd107b7e02c48fe3fc6f7)
=> Refresh onfido-java after onfido-openapi-spec update (d180edd)

.release.json, README.md, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/JSON.java, src/main/java/com/onfido/model/DocumentProperties.java, src/main/java/com/onfido/model/DocumentPropertiesBarcodeInner.java, src/main/java/com/onfido/model/DocumentWithDriverVerificationReportAllOfProperties.java, src/test/java/com/onfido/integration/ReportSchemasTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@8c793a1c8307dcd92fa657edb2a1e9b184c15278 (included)
- [Fix tests after library update](https://github.com/onfido/onfido-java/pull/136/commits/fb97669f54ca2d795368530e470bfdc9fa74187c)
=> Refresh onfido-java after onfido-openapi-spec update (8c793a1)

.release.json, README.md, build.gradle, build.sbt, media/studio_webhook_event_with_list_in_output.json, media/studio_webhook_event_with_object_in_output.json, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/model/Task.java, src/main/java/com/onfido/model/WebhookEventPayloadResource.java, src/main/java/com/onfido/model/WebhookEventResourceType.java, src/main/java/com/onfido/model/WebhookEventType.java, src/test/java/com/onfido/webhooks/WebhookStudioEventVerifierTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@964fb43a1bf211197ef7a45c230771b8ba561b3c (included)
- [Update tests after library refresh](https://github.com/onfido/onfido-java/pull/137/commits/87e5b48d92d07538c68b937aa13a9b249fb3bb7e)
=> Refresh onfido-java after onfido-openapi-spec update (964fb43)

.release.json, README.md, build.gradle, build.sbt, pom.xml, src/main/java/com/onfido/ApiClient.java, src/main/java/com/onfido/Configuration.java, src/main/java/com/onfido/model/IdNumber.java, src/main/java/com/onfido/model/WebhookEventPayloadResource.java, src/test/java/com/onfido/OnfidoTest.java, src/test/java/com/onfido/integration/PingTest.java
Auto-generated PR with changes till commit onfido/onfido-openapi-spec@be823e7815c93bfbfc3fb764c0548f57cb851fe9 (included)
- [Add basic test for the proxy functionality](https://github.com/onfido/onfido-java/pull/140/commits/aaf265f691d62364d8a00991cdb6bacb57ec2162)
=> Refresh onfido-java after onfido-openapi-spec update (be823e7)
